[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/consulta"
  to = "/"
  status = 301

[[redirects]]
  from = "/consulta/"
  to = "/"
  status = 301

[[redirects]]
  from = "/confirmacao"
  to = "/"
  status = 301

[[redirects]]
  from = "/confirmacao/"
  to = "/"
  status = 301

[[redirects]]
  from = "/confirmado"
  to = "/"
  status = 301

[[redirects]]
  from = "/confirmado/"
  to = "/"
  status = 301

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
